### PR TITLE
updating references

### PR DESCRIPTION
**Pull request by seanturner**

### CODE REVIEW

**Review by katrielalex — CHANGES_REQUESTED** [review]
Hmm, this is a broken link (see the [deploy preview](https://deploy-preview-8--mlswg.netlify.com/)). Are you intending to link to the raw md document on github i.e. [this](https://github.com/mlswg/mls-protocol/blob/master/draft-ietf-mls-protocol.md)?

**Comment by katrielalex** [comment]
PS oh, is this related to your other email about broken links?

**Comment by seanturner** [comment]
Kind of - there’s “Editor’s Copy” links broken on:
https://github.com/mlswg/mls-architecture
https://github.com/mlswg/mls-protocol

But, this is also about a broken link from https://mlswg.github.io/
to point to the different drafts.  I figured pointing to the md files was the right way to go.

spt

**Comment by katrielalex** [comment]
Gotcha. I suggest linking to the full URL (https://github.com/mlswg/mls-architecture/blob/master/draft-ietf-mls-architecture.md) here, and I'll go fix the editor's copy links to refer to that as well.

(The previous links worked when there was no mlswg.github.io repository, but now that I made that I think it shadows them.)

**Review by katrielalex — APPROVED** [review]

**Pull request merged**
